2025-05-25 00:37:09,165 ERROR: Error details: Traceback (most recent call last):
  File "C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py", line 2118, in patient_dashboard
    return render_template('patient_dashboard.html',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
           ^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\templates\patient_dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\templates\base.html", line 848, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\templates\patient_dashboard.html", line 123, in block 'content'
    name="appointment_date" required min="{{ now.strftime('%Y-%m-%dT%H:%M') }}">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\venv\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'now' is undefined
 [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:2130]
2025-05-25 00:37:09,192 ERROR: Error in patient dashboard: 'now' is undefined [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:2129]
2025-05-25 00:37:09,193 ERROR: Error details: Traceback (most recent call last):
  File "C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py", line 2118, in patient_dashboard
    return render_template('patient_dashboard.html',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
           ^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\venv\Lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\templates\patient_dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\templates\base.html", line 848, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\templates\patient_dashboard.html", line 123, in block 'content'
    name="appointment_date" required min="{{ now.strftime('%Y-%m-%dT%H:%M') }}">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\venv\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'now' is undefined
 [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:2130]
2025-05-25 00:42:37,682 INFO: Action: login_manual_password_success, User: Yehia, Details: Password verified for user Yehia. Proceeding to 2FA. [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:805]
2025-05-25 00:42:51,575 INFO: Action: login_manual_2fa_success, User: Yehia, Details: User Yehia successfully completed 2FA and logged in manually. [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:805]
2025-05-25 00:42:51,605 INFO: Accessing patient dashboard. Session data: {'_permanent': True, 'username': 'Yehia', 'role': 'patient', '_flashes': [('success', 'Successfully logged in')]} [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:2020]
2025-05-25 00:42:51,606 INFO: Successfully loaded dashboard for patient: Yehia [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:2098]
2025-05-25 00:49:35,032 INFO: Accessing patient dashboard. Session data: {'_permanent': True, 'username': 'Yehia', 'role': 'patient'} [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:2020]
2025-05-25 00:49:35,033 INFO: Successfully loaded dashboard for patient: Yehia [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:2098]
2025-05-25 00:50:08,147 INFO: Action: login_manual_password_success, User: admin, Details: Password verified for user admin. Proceeding to 2FA. [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:805]
2025-05-25 00:50:20,491 INFO: Action: login_manual_2fa_success, User: admin, Details: User admin successfully completed 2FA and logged in manually. [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:805]
2025-05-25 00:51:09,903 INFO: Action: admin_edit_user_success, User: admin, Details: Admin updated user ID 26 (Username: Yehia, Role: patient) [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:805]
2025-05-25 00:51:51,766 INFO: Action: profile_update, User: admin, Details: Updated profile information [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:805]
2025-05-25 00:52:08,813 INFO: Action: login_manual_password_success, User: Yehia, Details: Password verified for user Yehia. Proceeding to 2FA. [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:805]
2025-05-25 00:52:19,263 INFO: Action: login_manual_2fa_failed, User: Yehia, Details: User Yehia failed 2FA. Invalid code. [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:805]
2025-05-25 00:52:26,859 INFO: Action: login_manual_2fa_success, User: Yehia, Details: User Yehia successfully completed 2FA and logged in manually. [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:805]
2025-05-25 00:52:26,886 INFO: Accessing patient dashboard. Session data: {'_permanent': True, 'username': 'Yehia', 'role': 'patient', '_flashes': [('success', 'Successfully logged in')]} [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:2020]
2025-05-25 00:52:26,887 INFO: Successfully loaded dashboard for patient: Yehia [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:2098]
2025-05-25 00:52:48,642 INFO: Accessing patient dashboard. Session data: {'_permanent': True, 'username': 'Yehia', 'role': 'patient'} [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:2020]
2025-05-25 00:52:48,644 INFO: Successfully loaded dashboard for patient: Yehia [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:2098]
2025-05-25 00:52:51,141 INFO: Accessing patient dashboard. Session data: {'_permanent': True, 'username': 'Yehia', 'role': 'patient'} [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:2020]
2025-05-25 00:52:51,142 INFO: Successfully loaded dashboard for patient: Yehia [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:2098]
2025-05-25 00:52:55,935 INFO: Accessing patient dashboard. Session data: {'_permanent': True, 'username': 'Yehia', 'role': 'patient'} [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:2020]
2025-05-25 00:52:55,937 INFO: Successfully loaded dashboard for patient: Yehia [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:2098]
2025-05-25 00:53:08,487 INFO: Action: login_manual_password_success, User: sara, Details: Password verified for user sara. Proceeding to 2FA. [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:805]
2025-05-25 00:53:13,012 INFO: Action: login_manual_2fa_success, User: sara, Details: User sara successfully completed 2FA and logged in manually. [in C:\Users\yehia\OneDrive\Desktop\Info Final\INFO\app.py:805]
